// vuejs/src/components/Emit.vue
<template>
  <span>fill something here <input v-bind:value='value' v-on:input='change($event.target.value)'/> </span>
</template>

<script>
export default {
  name: 'emit',
  data: function () {
    return {
      _valueToEmit: 'toto'
    }
  },

  computed: {
    value: {
      get: function () {
        return this._valueToEmit
      },
      set: function (value) {
        this._valueToEmit = value
        this.$emit('value', value)
      }
    }
  },

  methods: {
    change: function (newValue) {
      this.value = newValue
    }
  },

  created: function () {
    console.info('%c emit content created', 'color: brown')
  },

  mounted: function () {
    console.info('%c emit content mounted', 'color: brown')
  },

  updated: function () {
    console.info('%c emit content updated', 'color: brown')
  }
}
</script>

<style scoped>
  span { color: brown }
</style>

// angular/src/app/sub/emit.component.ts
import { Component, Output, EventEmitter, AfterViewChecked, AfterContentChecked, OnInit } from '@angular/core';

/**
 * this component should re-render only when you fill something in the input text
 * 
 * why AfterViewChecked & AfterContentChecked are called each time CounterComponent
 * change ?
 */
@Component({
  selector: 'emit',
  template: `<span>fill something here <input [ngModel]='_valueToEmit' (ngModelChange)='change($event)'/> </span>`,
  styles: [`span { color: brown }`]
})
export class EmitComponent implements OnInit, AfterViewChecked, AfterContentChecked {
  protected _valueToEmit: string

  set valueToEmit(value) {
    this._valueToEmit = value
    this.value.emit(value)
  }

  @Output() value: EventEmitter<string> = new EventEmitter()

  constructor() {
      console.info('%c emit created', 'color: pink')
  }

  ngOnInit() {
      console.info('%c emit mounted', 'color: pink')
  }

  ngAfterViewChecked() {
    console.info('%c emit view checked', 'color: pink')
  }

  ngAfterContentChecked() {
    console.info('%c emit content checked', 'color: pink')
  }

  change(newValue) {
    this.valueToEmit = newValue
  }
}
