// vuejs/src/components/Alone.vue
<template>
  <span><span>I'm alone</span></span>
</template>

<script>
export default {
  name: 'alone',
  created: function () {
    console.info('%c alone content created', 'color: blue')
  },
  mounted: function () {
    console.info('%c alone content mounted', 'color: blue')
  },
  updated: function () {
    console.info('%c alone content updated', 'color: blue')
  }
}
</script>

<style scoped>
  span { color: blue }
</style>

// react/src/components/alone.js
import React, { Component } from "react";

export default class Alone extends Component {
  componentWillMount() {
    console.info('%c alone view created', 'color: blue')
  }

  componentDidMount() {
    console.info('%c alone view mounted', 'color: blue')
  }

  componentWillUpdate() {
    console.info('%c alone will updated', 'color: blue')
  }

  render() {
    const style = {
      color: 'blue'
    }

    return (
      <span style={style}>I'm alone</span>
    );
  }
}
