// vuejs/src/components/Emit.vue
<template>
  <span>fill something here <input v-bind:value='value' v-on:input='change($event.target.value)'/> </span>
</template>

<script>
export default {
  name: 'emit',
  data: function () {
    return {
      _valueToEmit: 'toto'
    }
  },

  computed: {
    value: {
      get: function () {
        return this._valueToEmit
      },
      set: function (value) {
        this._valueToEmit = value
        this.$emit('value', value)
      }
    }
  },

  methods: {
    change: function (newValue) {
      this.value = newValue
    }
  },

  created: function () {
    console.info('%c emit content created', 'color: brown')
  },

  mounted: function () {
    console.info('%c emit content mounted', 'color: brown')
  },

  updated: function () {
    console.info('%c emit content updated', 'color: brown')
  }
}
</script>

<style scoped>
  span { color: brown }
</style>

// react/src/components/emit.js
import React, { Component } from "react";

export default class Emit extends Component {
  constructor(props) {
    super(props);
    this.state = {
      value: ''
    };
  }

  componentWillMount() {
    console.info('%c emit content created', 'color: brown')
  }

  componentDidMount() {
    console.info('%c emit content mounted', 'color: brown')
  }

  componentWillUpdate() {
    console.info('%c emit content updated', 'color: brown')
  }

  handleChange(e) {
    const value = e.target.value
    this.setState({
      value: value
    });
    this.props.change(value)
  }

  render() {
    const { value } = this.state;
    const style = {
      color: 'brown'
    }

    return (
      <span style={style}>fill something here <input value={value} onChange={this.handleChange.bind(this)}/> </span>
    );
  }
}
