// vuejs/src/components/Subscribe.vue
<template>
  <ol>
    <li><span>display field value from emit component <cite v-if="value">: "{{value}}"</cite></span></li>
    <li><emit v-on:value='setValue($event)'></emit></li>
  </ol>
</template>

<script>
import Vue from 'vue'
import Emit from './Emit'
Vue.component('emit', Emit)

export default {
  name: 'subscribe',
  components: [
    Emit
  ],
  data: function () {
    return {
      value: ''
    }
  },

  methods: {
    setValue: function (value) {
      this.value = value
    }
  },

  created: function () {
    console.info('%c subscribe content created', 'color: blueviolet')
  },

  mounted: function () {
    console.info('%c subscribe content mounted', 'color: blueviolet')
  },

  updated: function () {
    console.info('%c subscribe content updated', 'color: blueviolet')
  }
}
</script>

<style scoped>
  span { color: blueviolet }
</style>

// react/src/components/subscribe.js
import React, { Component } from "react";
import Emit from "./emit"

export default class Subscribe extends Component {
  constructor(props) {
    super(props);
    this.state = {
      value: ''
    };
  }

  componentWillMount() {
    console.info('%c subscribe content created', 'color: blueviolet')
  }

  componentDidMount() {
    console.info('%c subscribe content mounted', 'color: blueviolet')
  }

  componentWillUpdate() {
    console.info('%c subscribe content updated', 'color: blueviolet')
  }

  updateValue(value) {
    this.setState({
      value: value
    });
  }

  render() {
    const { value } = this.state;
    const style = {
      color: 'blueviolet'
    }

    return (
      <ol>
        <li><span style={style}>display field value from emit component {value &&
          <cite>: "{value}"</cite>
        }</span></li>
        <li><Emit value={value} change={this.updateValue.bind(this)}></Emit></li>
      </ol>
    );
  }
}
