// angular/src/app/sub/subscribe.component.ts
import { Component, AfterViewChecked, AfterContentChecked, OnInit } from '@angular/core';

/**
 * this component should be re-rendered only when EmitComponent emit a new value
 * 
 * why AfterViewChecked & AfterContentChecked are called each time CounterComponent
 * change ?
 */
@Component({
  selector: 'subscribe',
  template: `
  <ol>
    <li><span>display field value from emit component <cite *ngIf="value">: "{{value}}"</cite></span></li>
    <li><emit (value)='setValue($event)'></emit></li>
  </ol>`,
  styles: [`span { color: blueviolet }`]
})
export class SubscribeComponent implements OnInit, AfterViewChecked, AfterContentChecked {
  protected value: string = ''

  setValue(value) {
    this.value = value
  }

  constructor() {
    console.info('%c subscribe created', 'color: blueviolet')
  }

  ngOnInit() {
    console.info('%c subscribe mounted', 'color: blueviolet')
  }

  ngAfterViewChecked() {
    console.info('%c subscribe view checked', 'color: blueviolet')
  }

  ngAfterContentChecked() {
    console.info('%c subscribe content checked', 'color: blueviolet')
  }
}

// vuejs/src/components/Subscribe.vue
<template>
  <ol>
    <li><span>display field value from emit component <cite v-if="value">: "{{value}}"</cite></span></li>
    <li><emit v-on:value='setValue($event)'></emit></li>
  </ol>
</template>

<script>
import Vue from 'vue'
import Emit from './Emit'
Vue.component('emit', Emit)

export default {
  name: 'subscribe',
  components: [
    Emit
  ],
  data: function () {
    return {
      value: ''
    }
  },

  methods: {
    setValue: function (value) {
      this.value = value
    }
  },

  created: function () {
    console.info('%c subscribe content created', 'color: blueviolet')
  },

  mounted: function () {
    console.info('%c subscribe content mounted', 'color: blueviolet')
  },

  updated: function () {
    console.info('%c subscribe content updated', 'color: blueviolet')
  }
}
</script>

<style scoped>
  span { color: blueviolet }
</style>
